#!/usr/bin/env bash

source create_passwd
NAMESPACE=${1:=default}

cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: $(hostname)-secret
  namespace: $NAMESPACE
  labels:
    job: $(hostname)
data:
  password: $(echo "$PASSWORD" | base64 )
EOF
